### ISSUE TITLE
Can you upload this to Unreal Maketplace?

### ISSUE THREAD

**Issue by faxlab** [Urkaz/UnusedNodeCleaner#1] opened 2023-02-27 17:10 UTC
So I can easily enable/disable it for my projects? Thanks

**Comment by Urkaz** [comment] 2023-03-02 22:11
Hi, there was a bug on the Epic Games Launcher, that did not allow anyone to download the plugin.

The problem is already resolved by Epic and the plugin should be downloadable again from the Launcher.

**Closed as completed by Urkaz** 2023-03-02 22:11 UTC
Labels: bug

**Comment by faxlab** [comment] 2023-03-03 12:23
Thx
